name: Test CD

on:
  push:
    branches: [ master ]

env:
  SERVER_HOST: 34.239.114.247
  SERVER_USERNAME: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        # port: 22
        # script: |
        #   cd Wallet-App-API/  

# pm2 restart wallet-app
# git pull
# npm install