name: Test CD

on:
  push:
    branches: [ master ]

env:
  SERVER_HOST: 3.76.103.210
  SERVER_USERNAME: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/Wallet-App-API/
          git pull
          /usr/bin/node -v
          /usr/bin/npm -v
          /usr/bin/npm install
          /usr/bin/npm run build

# pm2 restart wallet-app
